const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../monitor-v2.html'),'utf8');
const start=html.indexOf('    function blockedWrite()');
const code=html.slice(start,html.indexOf('\n    // ⭐ Publish SOP',start));
function sdk(existing,fail=false){let writes=0,reads=0;const c={db:{},runTransaction:async(_,f)=>f({get:async()=>{reads++;if(fail)throw Error('synthetic read failure');return {exists:()=>!!existing,data:()=>existing};},set:()=>writes++})};vm.createContext(c);vm.runInContext(code,c);return {c,writes:()=>writes,reads:()=>reads};}
for(const p of ['cashbook/active','upah/active','sop_status/pohon_cabut','sop_status/compliance','sop_status/kasbon','sop_status/pupuk','sop_master/active','panen_data/active','panen_sampling/active','panen_lots/active','worker_tokens/TEST','worker_defs_custom/active','distribusi_pic/active','milestones/active','opt_observations/active']){
 test('blocked dashboard singleton '+p+' regardless of stale/loaded/failed client',async()=>{for(const state of [null,{revision:42}, {revision:0}]){const h=sdk(state);await assert.rejects(h.c.setDoc({path:p},{data:[{id:'seed'}]}));assert.equal(h.writes(),0);assert.equal(h.reads(),0);}});
}
test('dashboard update and deletion unavailable',async()=>{const h=sdk(null);await assert.rejects(h.c.updateDoc());await assert.rejects(h.c.deleteDoc());assert.equal(h.writes(),0);});
test('dashboard lost ACK retry preserves edited report',async()=>{const h=sdk({id:'one',created_at:'t',detail:'edited'});assert.equal(await h.c.setDoc({path:'laporan/one'},{id:'one',created_at:'t',detail:'old'}),'one');assert.equal(h.writes(),0);});
test('dashboard read failure fails closed',async()=>{const h=sdk(null,true);await assert.rejects(h.c.setDoc({path:'laporan/one'},{id:'one',created_at:'t'}));assert.equal(h.writes(),0);});
test('dashboard ID conflict fails closed',async()=>{const h=sdk({id:'one',created_at:'other'});await assert.rejects(h.c.setDoc({path:'laporan/one'},{id:'one',created_at:'t'}));assert.equal(h.writes(),0);});
function queue(){let value='[]';const events={};const c={window:{addEventListener:()=>{}},document:{addEventListener:(type,f)=>{events[type]=f;}},localStorage:{getItem:()=>value,setItem:(_,v)=>{value=v;}},console:{warn:()=>{}},alert:()=>{}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(__dirname,'../recovery/entry-recovery.js'),'utf8'),c);return {c,q:c.window.entryRecovery,events};}
test('staff missing SDK retains durable pending',async()=>{const h=queue();h.q.enqueue([{id:'one',created_at:'t'}]);await h.q.drain();assert.equal(h.q.pending().length,1);});
test('staff wrong ACK retained',async()=>{const h=queue();h.q.enqueue([{id:'one',created_at:'t'}]);h.c.window.syncLaporanEntryToFirestore=async()=>false;await h.q.drain();assert.equal(h.q.pending().length,1);});
test('staff queue single-flight preserves append during drain',async()=>{const h=queue();let release,calls=0;const gate=new Promise(r=>release=r);h.q.enqueue([{id:'one',created_at:'t'}]);h.c.window.syncLaporanEntryToFirestore=async e=>{calls++;await gate;return e.id;};const a=h.q.drain(),b=h.q.drain();await new Promise(r=>setImmediate(r));h.q.enqueue([{id:'two',created_at:'t'}]);release();await Promise.all([a,b]);assert.equal(calls,1);assert.equal(h.q.pending()[0].id,'two');});
