// Submitted-content identity regression; synthetic transport, no cloud calls.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const h=fs.readFileSync(require('node:path').join(__dirname,'../lapor.html'),'utf8');
function harness(){let writes=0,lost=true;const docs=new Map();const c=vm.createContext({window:{},db:{},COLLECTIONS:{laporan:'laporan'},doc:(_,coll,id)=>({id}),serverTimestamp:()=>123,runTransaction:async(_,callback)=>{const pending=[];await callback({get:async ref=>({exists:()=>docs.has(ref.id),data:()=>docs.get(ref.id)}),set:(ref,data)=>pending.push([ref.id,structuredClone(data)])});for(const [id,data] of pending){docs.set(id,data);writes++;}if(lost&&pending.length){lost=false;throw Error('synthetic lost ACK');}}});vm.runInContext(h.match(/function workerReportContent\(value\) \{[\s\S]*?\n\}/)[0],c);vm.runInContext(h.match(/window\.firestorePush = async \(entryData, localId\) => \{[\s\S]*?\n    \};/)[0],c);return {push:c.window.firestorePush,docs,get writes(){return writes}};}
const entry=()=>({id:'unique',created_at:'same',pelapor:'KUMPUL',photos:['a','b'],nested:{a:1,b:2}});
test('real push lost ACK retries same content without duplicate write',async()=>{const s=harness(),e=entry();await assert.rejects(s.push(e),/lost ACK/);assert.equal(await s.push({...e,nested:{b:2,a:1}}),e.id);assert.equal(s.writes,1);});
test('extra remote content cannot be acknowledged or overwritten',async()=>{const s=harness(),e=entry();s.docs.set(e.id,{...e,other:'divergent'});await assert.rejects(s.push(e),/Konflik/);assert.equal(s.writes,0);assert.equal(s.docs.get(e.id).other,'divergent');});
test('array order is part of submitted revision',async()=>{const s=harness(),e=entry();s.docs.set(e.id,{...e,photos:['b','a']});await assert.rejects(s.push(e),/Konflik/);assert.equal(s.writes,0);});
test('two legitimate distinct IDs with identical bodies never collapse',async()=>{const s=harness(),a=entry(),b={...a,id:'second'};await assert.rejects(s.push(a),/lost ACK/);await s.push(b);await s.push(a);assert.equal(s.docs.size,2);assert.equal(s.writes,2);});
